services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kasungihan/password-app
    ports:
      - 3000:8000
    volumes:
      - ./:/var/www/html
    #command: npm start
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      #- ./nginx:/etc/nginx/conf.d/default.conf:ro
